# Generated by Django 2.2.7 on 2019-11-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20191123_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='1.jpg', upload_to='images/'),
        ),
    ]
