# Generated by Django 2.2.6 on 2019-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='pair',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
