# Generated by Django 2.2.7 on 2019-11-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191123_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='split',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
