# Generated by Django 2.2.7 on 2019-11-24 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20191123_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='split',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('a', 'paid by you and split equally'), ('b', 'paid by your friend and split equally'), ('c', 'You owe to him completely'), ('d', 'He owe to you completely'), ('e', 'Split by percentages'), ('f', 'Split by shares')], default='green', max_length=10),
        ),
    ]
