# Generated by Django 2.2.7 on 2019-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20191124_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='group',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
