# Generated by Django 2.2.6 on 2019-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20191124_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_group',
            name='users',
            field=models.ManyToManyField(to='accounts.Pair'),
        ),
        migrations.AlterField(
            model_name='group_member',
            name='group_members',
            field=models.ManyToManyField(to='accounts.Add_group'),
        ),
    ]
