# Generated by Django 2.2.6 on 2019-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20191124_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_transactions',
            name='Description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group_transactions',
            name='Tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group_transactions',
            name='amt_for_him',
            field=models.CharField(blank=True, max_length=10000000),
        ),
        migrations.AddField(
            model_name='group_transactions',
            name='amt_paid_by_him',
            field=models.CharField(blank=True, max_length=10000000),
        ),
        migrations.AlterField(
            model_name='add_group',
            name='users',
            field=models.ManyToManyField(to='accounts.Pair'),
        ),
        migrations.RemoveField(
            model_name='group_transactions',
            name='group',
        ),
        migrations.AddField(
            model_name='group_transactions',
            name='group',
            field=models.ManyToManyField(to='accounts.Add_group'),
        ),
    ]
