# Generated by Django 2.2.6 on 2019-11-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20191124_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_transactions',
            name='add_group_key',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='add_group',
            name='users',
            field=models.ManyToManyField(to='accounts.Pair'),
        ),
        migrations.AlterField(
            model_name='group_transactions',
            name='group',
            field=models.ManyToManyField(to='accounts.Add_group'),
        ),
    ]
