# Generated by Django 2.2.6 on 2019-11-25 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20191125_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_transactions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_transactions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='add_group',
            name='users',
            field=models.ManyToManyField(to='accounts.Pair'),
        ),
        migrations.AlterField(
            model_name='group_transactions',
            name='group',
            field=models.ManyToManyField(to='accounts.Add_group'),
        ),
    ]
