# Generated by Django 2.2.6 on 2019-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20191125_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_group',
            name='users',
            field=models.ManyToManyField(to='accounts.Pair'),
        ),
        migrations.AlterField(
            model_name='group_transactions',
            name='group',
            field=models.ManyToManyField(to='accounts.Add_group'),
        ),
    ]
