# Generated by Django 2.2.6 on 2019-11-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_id',
        ),
    ]
