# Generated by Django 2.2.6 on 2019-11-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191113_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_member',
            old_name='groups',
            new_name='group_members',
        ),
    ]
