# Generated by Django 2.2.7 on 2019-11-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_transactions_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='current_user_pk',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
