# Generated by Django 2.2.7 on 2019-11-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_transactions_current_user_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_friend',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount_you',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='split',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('a', 'paid by you and split equally'), ('b', 'paid by your friend and split equally'), ('c', 'You owe to him completely'), ('d', 'He owe to you completely'), ('e', (('1', 'paid by you and split by shares'), ('2', 'paid by friend and split by shares'), ('3', 'paid by you and split by percentages'), ('4', 'paid by friend and split by percentages')))], default='green', max_length=10),
        ),
    ]
